In [7]:
import numpy as np
import pandas as pd
from sklearn.externals import joblib

model1=joblib.load('John_Madden.joblib') 
model2=joblib.load('Shotgun.joblib') 
model3=joblib.load('Pro_Set.joblib') 
game_data = pd.read_csv('Week7&8.csv')
game_data.head()

,Week,Home,Away,HomeLine,PredictTotal,HOME_OFFPass_DVOA,HOME_OFFRush_DVOA,HOME_DEFPassDVOA,HOME_DEFRushDVOA,HOME_STDVOA,VISIT_OFFPass_DVOA,VISIT_OFFRush_DVOA,VISIT_DEFPassDVOA,VISIT_DEFRushDVOA,VISIT_STDVOA
0,7,DEN,KC,4.5,50.5,-0.071833,-0.031833,0.049833,-0.192500,-0.043500,0.567167,-0.092000,0.040833,0.055333,-0.010500
1,7,GB,LARD,-7.0,46.0,0.246333,0.059833,-0.196000,-0.015000,0.002500,0.241200,0.071600,0.226400,-0.237800,-0.008000
2,7,ATL,LARM,4.0,52.5,0.254333,-0.163333,0.544667,-0.185167,-0.040833,0.070667,0.078167,0.166833,-0.226500,-0.009667
3,7,WAS,SF,9.5,43.0,-0.155833,-0.288667,0.185667,-0.015000,0.019500,0.155417,0.026667,-0.772583,-0.144167,-0.036250
4,7,IND,HOU,-2.5,47.5,0.154200,0.010800,0.141200,0.029200,-0.034800,0.235833,0.017667,0.033000,-0.110000,-0.004833

In [11]:
week7X = game_data[['HomeLine', 'PredictTotal', 'HOME_OFFPass_DVOA', 'HOME_OFFRush_DVOA', 'HOME_DEFPassDVOA', 'HOME_DEFRushDVOA', 'HOME_STDVOA', 'VISIT_OFFPass_DVOA', 'VISIT_OFFRush_DVOA', 'VISIT_DEFPassDVOA', 'VISIT_DEFRushDVOA', 'VISIT_STDVOA']]
diffGuess = model1.predict(week7X)
betGuess = model2.predict(week7X)
classedGuess = model3.predict(week7X)
diffGuess

array([ -8.32187653,   4.54929909,  -6.23637873, -18.10339595,
        -2.48977926,  -2.57646165,  -8.28845856,   1.17579611,
        21.19509844,  -2.10437874,   2.58741006,   0.37193492,
         1.41371812, -18.5885805 ])

In [12]:
diffGuesses = pd.DataFrame({"Madden Differential": diffGuess, "Bet Home/Away": betGuess, "Class Guess":classedGuess})[["Madden Differential", "Bet Home/Away", "Class Guess"]]
diffGuesses

    Madden Differential  Bet Home/Away  Class Guess
0             -8.321877              0           -7
1              4.549299              0            7
2             -6.236379              1           -3
3            -18.103396              0          -20
4             -2.489779              0           -3
5             -2.576462              0           -4
6             -8.288459              0           -7
7              1.175796              0            3
8             21.195098              1           25
9             -2.104379              0            3
10             2.587410              1            7
11             0.371935              0            3
12             1.413718              0           10
13           -18.588581              0          -20

In [14]:
nice = pd.concat([game_data, diffGuesses], axis=1, sort=False)
cleaned = nice[["Home","Away","HomeLine","PredictTotal","Madden Differential", "Bet Home/Away", "Class Guess"]]
games = cleaned.dropna()
games.head()

,Home,Away,HomeLine,PredictTotal,Madden Differential,Bet Home/Away,Class Guess
0,DEN,KC,4.5,50.5,-8.321877,0,-7
1,GB,LARD,-7.0,46.0,4.549299,0,7
2,ATL,LARM,4.0,52.5,-6.236379,1,-3
3,WAS,SF,9.5,43.0,-18.103396,0,-20
4,IND,HOU,-2.5,47.5,-2.489779,0,-3